stackabletech/opa-operator

.github/pull_request_template.md, .github/workflows/rust.yml, deny.toml
Currently we run cargo-audit on pull requests as well as once per day.
This only checks for security advisories, but we'd also like to ensure that all our dependencies are licensed under compatible licenses, so we added a cargo deny check on pull request. This also scans for security advisories, so we can remove the audit action on PRs. But we will keep in daily, because this action opens issues on the repository, which is nice.
Also added a PR template with some common checks to do before signing of a PR.
=> Added cargo deny action to run on PR & PR template

crd/src/error.rs, crd/src/util.rs, operator/src/error.rs, operator/src/lib.rs
Rust 1.54 introduced some new Clippy warnings. This PR fixes all of those
=> Fix clippy warnings in 1.54

CHANGELOG.md, Cargo.lock, deploy/crd/openpolicyagent.crd.yaml, rust/crd/Cargo.toml, rust/crd/src/lib.rs, rust/crd/src/util.rs, rust/operator-binary/Cargo.toml, rust/operator-binary/src/stackable-opa-operator.rs, rust/operator/Cargo.toml, rust/operator/src/lib.rs
=> Adapted to kube-rs 0.60 and operator-rs 0.2.2.

CHANGELOG.md, Cargo.lock, README.adoc, deploy/crd/openpolicyagent.crd.yaml, docs/modules/ROOT/pages/index.adoc, docs/modules/ROOT/pages/usage.adoc, examples/simple-opacluster.yaml, rust/crd/Cargo.toml, rust/crd/src/discovery.rs, rust/crd/src/lib.rs, rust/operator-binary/Cargo.toml, rust/operator-binary/src/stackable-opa-operator.rs, rust/operator/Cargo.toml, rust/operator/src/lib.rs
fixes https://github.com/stackabletech/opa-operator/issues/118
=> Use docker image

CHANGELOG.md, Cargo.lock, deploy/helm/opa-operator/crds/crds.yaml, docs/modules/opa/examples/getting_started/opa.yaml, docs/modules/opa/examples/getting_started/opa.yaml.j2, docs/modules/opa/pages/usage.adoc, rust/crd/Cargo.toml, rust/operator-binary/Cargo.toml, rust/operator-binary/src/controller.rs, rust/operator-binary/src/main.rs, tests/templates/kuttl/cluster-operation/10-install-opa.yaml.j2, tests/templates/kuttl/cluster-operation/20-stop-opa.yaml.j2, tests/templates/kuttl/cluster-operation/30-pause-opa.yaml.j2, tests/templates/kuttl/cluster-operation/40-restart-opa.yaml.j2, tests/templates/kuttl/logging/02-install-opa.yaml.j2, tests/templates/kuttl/resources/10-install-opa.yaml.j2, tests/templates/kuttl/smoke/10-install-opa.yaml.j2, tests/test-definition.yaml
Part of https://github.com/stackabletech/issues/issues/404
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> feat: Default stackableVersion to operator version

CHANGELOG.md, Cargo.lock, Cargo.toml, deploy/helm/opa-operator/crds/crds.yaml, docs/modules/opa/examples/getting_started/opa.yaml, docs/modules/opa/examples/getting_started/opa.yaml.j2, docs/modules/opa/partials/supported-versions.adoc, rust/operator-binary/src/controller.rs, tests/templates/kuttl/cluster-operation/10-install-opa.yaml.j2, tests/templates/kuttl/cluster-operation/20-stop-opa.yaml.j2, tests/templates/kuttl/cluster-operation/30-pause-opa.yaml.j2, tests/templates/kuttl/cluster-operation/40-restart-opa.yaml.j2, tests/templates/kuttl/logging/01-install-opa-vector-aggregator.yaml, tests/templates/kuttl/smoke/10-install-opa.yaml.j2, tests/test-definition.yaml
- added support for version 0.57.0
- removed support for versions 0.45.0, 0.41.0, 0.37.2, 0.28.0, 0.27.1
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Add new version 0.57.0

CHANGELOG.md, Cargo.lock, Cargo.toml, deploy/helm/opa-operator/crds/crds.yaml, docs/modules/opa/pages/usage-guide/operations/graceful-shutdown.adoc, rust/crd/src/lib.rs, rust/operator-binary/Cargo.toml, rust/operator-binary/src/controller.rs, rust/operator-binary/src/main.rs, rust/operator-binary/src/operations/graceful_shutdown.rs, rust/operator-binary/src/operations/mod.rs, tests/templates/kuttl/smoke/10-assert.yaml, tests/templates/kuttl/smoke/10-assert.yaml.j2
Part of https://github.com/stackabletech/issues/issues/357
Closes https://github.com/stackabletech/opa-operator/issues/489
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> feat: Support graceful shutdown

Cargo.lock, Cargo.nix, Cargo.toml, crate-hashes.json, rust/operator-binary/src/controller.rs
Forward the correct log level to log processing. `to_opa_literal()` converts to opa log levels, which only include a subset of possible log levels, and this results in undesired behavior. For example `LogLevel::NONE` would be converted to `error`, which means error logs would not be filtered out. This PR fixes that.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> fix: forward the correct log level to log processing

docs/modules/opa/pages/usage.adoc
docs: remove home module from refs (stackabletech/documentation#637)
=> docs: remove home module from refs (stackabletech/documentation#637) / 23.1

docs/modules/opa/pages/usage.adoc
docs: remove home module from refs (stackabletech/documentation#637) / 23.4
=> docs: remove home module from refs (stackabletech/documentation#637) / 23.4

docs/modules/opa/pages/usage.adoc
docs: remove home module from refs (stackabletech/documentation#637) / 23.7
=> docs: remove home module from refs (stackabletech/documentation#637) / 23.7

tests/templates/kuttl/logging/02-create-configmap-with-prepared-logs.yaml, tests/templates/kuttl/logging/03-install-opa.yaml.j2, tests/templates/kuttl/logging/prepared-bundle-builder-logs.tracing-rs.json, tests/templates/kuttl/logging/prepared-bundle-builder-logs.txt
* Adapt the logging test to the bundle builder v2
* Create the log directory for the opa container upfront to avoid a race condition
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Adapt the logging test to the bundle builder v2

deploy/helm/opa-operator/templates/roles.yaml
See: https://github.com/stackabletech/issues/issues/624
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> fix(helm): use same scc as olm

tests/templates/kuttl/aas-user-info/10-install-opa.yaml.j2, tests/templates/kuttl/aas-user-info/30-assert.yaml, tests/templates/kuttl/aas-user-info/test-regorule.py, tests/templates/kuttl/keycloak-user-info/10-install-opa.yaml.j2, tests/templates/kuttl/keycloak-user-info/30-assert.yaml, tests/templates/kuttl/keycloak-user-info/test-regorule.py
Fixes the [test failures] (see [slack thread]):
_The effective fixes were cd3c31ed8bfff588fe2cc68c23a258a080f5ce65 and 7c308cc6f0959ffe353bab57ebd4a590cbf20866_
```
Traceback (most recent call last):
File "/tmp/test-regorule.py", line 60, in <module>
raise e
File "/tmp/test-regorule.py", line 50, in <module>
something went wrong. last response: {'result': {}}
assertions(username, response, 
```
- Use the bundled userinfo rego utility (partially reverts #580)
- Improve the output of the test scripts
- print out the exception, it will have more information (from the `assertions()` function).
- ruff formatting
[test failures]: https://testing.stackable.tech/job/opa-operator-it-weekly/13/console
[slack thread]: https://stackable-workspace.slack.com/archives/C02M1RE8S0Z/p1723187622613479
=> fix(kuttl tests): Use bundled userinfo rego utility

docs/modules/opa/examples/getting_started/getting_started.sh, docs/modules/opa/examples/getting_started/install_output.txt
Part of https://github.com/stackabletech/issues/issues/647.
=> docs: Update release in getting_started

.github/workflows/build.yml, CHANGELOG.md, Cargo.lock, rust/operator-binary/src/controller.rs, tests/templates/kuttl/smoke/10-assert.yaml.j2
Part of <https://github.com/stackabletech/issues/issues/527>
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> feat: run containerdebug in the background

Cargo.lock, Cargo.nix, rust/user-info-fetcher/src/main.rs
Fixes https://github.com/stackabletech/opa-operator/issues/692.
There was a regression introduced in native-tls 0.2.13.
Before:
```
Error: ConstructHttpClient { source: reqwest::Error { kind: Builder, source: Normal(ErrorStack(])) } }
```
After:
```
Error: failed to construct http client
Caused by these errors (recent errors listed first):
1: builder error
2: OpenSSL error
```
=> chore: Add snafu::report to get better error detail

docs/modules/opa/examples/getting_started/opa.yaml, docs/modules/opa/examples/getting_started/opa.yaml.j2
Part of <https://github.com/stackabletech/issues/issues/697>
This PR bumps the following:
- `opa` to 1.0.1
```shell
kind delete cluster && kind create cluster
./getting_started.sh stackablectl
kind delete cluster && kind create cluster
./getting_started.sh helm
```
=> chore(docs): Update getting-started script pre-25.3.0

CHANGELOG.md, Cargo.lock, Cargo.nix, deny.toml, rust/operator-binary/src/controller.rs, tests/templates/kuttl/ad-user-info/00-limit-range.yaml, tests/templates/kuttl/ad-user-info/00-patch-ns.yaml.j2, tests/templates/kuttl/ad-user-info/01-assert.yaml.j2, tests/templates/kuttl/ad-user-info/01-install-vector-aggregator-discovery-configmap.yaml.j2, tests/templates/kuttl/ad-user-info/10-assert.yaml, tests/templates/kuttl/ad-user-info/10-install-opa.yaml.j2, tests/templates/kuttl/ad-user-info/20-assert.yaml, tests/templates/kuttl/ad-user-info/20-install-test-regorule.yaml, tests/templates/kuttl/ad-user-info/30-assert.yaml, tests/templates/kuttl/ad-user-info/30-prepare-test-regorule.yaml, tests/templates/kuttl/ad-user-info/test-regorule.py, tests/test-definition.yaml
Fixes #680
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> Use service scope for user-info-fetcher AD kerberos keytab

CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, deploy/helm/opa-operator/Chart.yaml, deploy/helm/opa-operator/crds/crds.yaml, docs/antora.yml, docs/modules/opa/examples/getting_started/getting_started.sh, docs/modules/opa/examples/getting_started/install_output.txt, docs/templating_vars.yaml, tests/release.yaml
=> chore: Release 25.3.0

CHANGELOG.md, rust/bundle-builder/src/main.rs, rust/operator-binary/src/main.rs, rust/user-info-fetcher/src/main.rs
This was accidentally broken by work done in https://github.com/stackabletech/issues/issues/639 but before https://github.com/stackabletech/operator-rs/pull/1001 could be rolled out (which does use the correct file extension).
```
--- PASS: kuttl (67.73s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/logging_opa-1.0.1_openshift-false (67.72s)
PASS
```
=> fix: Use `json` file extension for log files

CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, crate-hashes.json, rust/operator-binary/src/controller.rs
Part of https://github.com/stackabletech/issues/issues/639
=> chore!: Bump stackable-operator to 0.92.0

tests/templates/kuttl/ad-user-info/20-install-test-regorule.yaml
Part of https://github.com/stackabletech/infrastructure/issues/142
Repository references were already updated for this repo with changelog entry already present, new old docker.stackable.tech reference was added after, this PR fixes that.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> chore: update to oci references

docs/modules/opa/examples/getting_started/getting_started.sh, docs/modules/opa/examples/getting_started/getting_started.sh.j2, docs/modules/opa/pages/getting_started/installation.adoc, docs/templating_vars.yaml
Part of https://github.com/stackabletech/infrastructure/issues/142
Updating the helm install commands in Getting started sections of the operators was missed during Harbor migration of the docs.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
=> docs: Update helm install commands

CHANGELOG.md, tests/templates/kuttl/logging/01-install-opa-vector-aggregator.yaml
Part of https://github.com/stackabletech/docker-images/issues/1085.
- Bump to Vector 0.46.1 (chart version 0.42.1) in tests
=> test: Bump vector to 0.46.1

CHANGELOG.md, docs/modules/opa/examples/getting_started/opa.yaml, docs/modules/opa/examples/getting_started/opa.yaml.j2, docs/modules/opa/partials/supported-versions.adoc, tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/1084.
- Add: `1.4.2`
- Deprecate: `1.0.1`
- Remove: `0.67.1`
=> chore: Add support for 1.4.2, deprecate 1.0.1, remove 0.67.1

CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, crate-hashes.json, rust/user-info-fetcher/src/backend/keycloak.rs
Part of https://github.com/stackabletech/issues/issues/642.
Bump stackable-operator to 0.93.0 which versions common CRD structs.
=> chore: Bump stackable-operator to 0.93.0 and bump deps

CHANGELOG.md, rust/operator-binary/src/controller.rs
Part of https://github.com/stackabletech/issues/issues/651
Remove hardcoded uid and gid, they'll default to the ones from the docker images now.
For 25.7 that means they might change from 1000/0
See https://github.com/stackabletech/docker-images/pull/916 for details
=> chore: Remove hardcoded uid and gid

docs/modules/opa/pages/index.adoc
done via https://github.com/stackabletech/issues/issues/47
Not sure if this renders correctly, anyone mind checking?
`xref:nifi:usage-guide/security.adoc#authorization-opa[Apache NiFi]` without the `_authorization..` part?
=> Docs: Add NiFi to supported products

tests/templates/kuttl/cluster-operation/10-assert.yaml, tests/templates/kuttl/logging/03-assert.yaml, tests/templates/kuttl/resources/10-assert.yaml.j2
Sometimes it takes longer than 5 minutes for all the OPA pods to be ready in our weekly tests.
=> tests: increase DaemonSet assert timeouts

CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, crate-hashes.json, deploy/helm/opa-operator/crds/crds.yaml, deploy/helm/opa-operator/templates/roles.yaml, rust/bundle-builder/src/main.rs, rust/operator-binary/src/crd/mod.rs, rust/operator-binary/src/main.rs
Part of <https://github.com/stackabletech/issues/issues/725>
> [!NOTE]
> During a Stackable release we need to update various Rust dependencies before
> entering the final release period to ensure we run the latest versions of
> crates. These bumps also include previously updated and released crates from
> the `operator-rs` repository.
> [!NOTE]
> The bumping / updating of Rust dependencies is done in multiple steps:
>
> 1. Update the minimum Version in the root `Cargo.toml` manifest.
> 2. Run the `cargo update` command, which also updates the `Cargo.lock` file.
> 3. Lastly, run `make regenerate-nix` to update the `Cargo.nix` file.
=> chore: Bump Rust dependencies pre-25.7.0

CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, deploy/helm/opa-operator/Chart.yaml, deploy/helm/opa-operator/crds/crds.yaml, docs/antora.yml, docs/modules/opa/examples/getting_started/getting_started.sh, docs/modules/opa/examples/getting_started/install_output.txt, docs/templating_vars.yaml, tests/release.yaml
=> chore: Release 25.7.0-rc1

CHANGELOG.md, deploy/helm/opa-operator/templates/roles.yaml
Needed since https://github.com/stackabletech/operator-rs/pull/938
Not 100% sure why the product needs this, but it was this way before.
Also, fix a wrongly placed "patch"
=> fix: Add RBAC permission to patch events

CHANGELOG.md, Cargo.lock, Cargo.nix, Cargo.toml, deploy/helm/opa-operator/Chart.yaml, docs/modules/opa/examples/getting_started/getting_started.sh, docs/modules/opa/examples/getting_started/install_output.txt, docs/templating_vars.yaml, tests/release.yaml
=> chore: Release 25.7.0

CHANGELOG.md, docs/modules/opa/pages/usage-guide/user-info-fetcher.adoc
Part of https://github.com/stackabletech/opa-operator/issues/751
Grepped the repo for `experimental`
=> chore: Mark user-info-fetcher as non-experimental

CHANGELOG.md, rust/operator-binary/src/controller.rs, tests/templates/kuttl/smoke/10-install-opa.yaml.j2, tests/templates/kuttl/smoke/32-assert.yaml
- env variables and therefore env_overrides were not considered from product config machinery
=> fix: Add ENV to product config machinery to fix env overrides
