stackabletech/opa-operator

- Cargo.lock
- deploy/config-spec/properties.yaml
- deploy/crd/opa.crd.yaml
- docs/modules/ROOT/nav.adoc
- docs/modules/ROOT/pages/commandline_args.adoc
- docs/modules/ROOT/pages/configuration.adoc
- docs/modules/ROOT/pages/usage.adoc
- examples/simple-opacluster.yaml
- opa-operator.iml
- operator/src/error.rs
- operator/src/lib.rs
- server/Cargo.toml
- server/packaging/buildrpm.sh
- server/packaging/copy_assets.py
- server/packaging/rpm/SOURCES/stackable-opa-operator-server-VERSION/usr/lib/systemd/system/stackable-opa-operator-server.service
- server/packaging/rpm/SPECS/stackable-opa-operator-server.spec
- server/src/main.rs
- Added should_be_scraped annotation
- Added finalizer
- Added container port
- Adapted to product_config_path from operator-rs
> Enabled monitoring 

- Cargo.lock
- crd/Cargo.toml
- deny.toml
- operator/Cargo.toml
- server/Cargo.toml
- server/src/main.rs
Fixes #58, fixes #57, prepares for release
> Fixes #58, fixes #57, prepares for release

- CHANGELOG.md
- Cargo.lock
- deploy/crd/openpolicyagent.crd.yaml
- rust/crd/Cargo.toml
- rust/crd/src/lib.rs
- rust/operator-binary/Cargo.toml
- rust/operator/Cargo.toml
- rust/operator/src/lib.rs
> Implemented versioning from operator-rs.

- CHANGELOG.md
- Cargo.lock
- rust/crd/Cargo.toml
- rust/operator-binary/Cargo.toml
- rust/operator/Cargo.toml
Release 0.4.0. DO NOT SQUASH MERGE!
> Release 0.4.0

- Cargo.lock
- deploy/crd/openpolicyagent.crd.yaml
- rust/crd/Cargo.toml
- rust/crd/src/lib.rs
- rust/operator-binary/Cargo.toml
- rust/operator/Cargo.toml
- rust/operator/src/lib.rs
> Use sticky scheduler.

- CHANGELOG.md
- Cargo.lock
- rust/crd/src/discovery.rs
- rust/crd/src/lib.rs
- rust/operator/Cargo.toml
- Renamed util to discovery (added deprecated reexport)
- Updated dependecies.
> Added common traits to discovery structs. 

- CHANGELOG.md
- Cargo.lock
- rust/crd/Cargo.toml
- rust/operator-binary/Cargo.toml
- rust/operator/Cargo.toml
Release 0.5.0. DO NOT SQUASH MERGE!
> Release 0.5.0

- CHANGELOG.md
- deploy/config-spec/properties.yaml
- rust/crd/src/lib.rs
> Removed last "reporule" references.

- CHANGELOG.md
- Cargo.lock
- deploy/helm/opa-operator/Chart.yaml
- deploy/manifests/configmap.yaml
- deploy/manifests/deployment.yaml
- deploy/manifests/serviceaccount.yaml
- rust/crd/Cargo.toml
- rust/operator-binary/Cargo.toml
- rust/operator/Cargo.toml
Release 0.6.0. DO NOT SQUASH MERGE!
> Release 0.6.0

- CHANGELOG.md
- Cargo.lock
- deploy/crd/openpolicyagent.crd.yaml
- examples/simple-opacluster.yaml
- rust/crd/Cargo.toml
- rust/crd/src/lib.rs
- rust/operator-binary/Cargo.toml
- rust/operator-binary/src/controller.rs
- rust/operator-binary/src/main.rs
- Adapted to operator-rs 0.8.0
- Removed StructOpts
- Adapted custom resource example to regorule cluster ip service
- Updated dependencies
Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)
> Adapted to operator-rs 0.8.0

- rust/operator-binary/src/controller.rs
- rust/operator-binary/src/discovery.rs
Fixes broken rustoc
Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)
> Rustdoc fixes

- CHANGELOG.md
- rust/operator-binary/src/controller.rs
Fixes https://github.com/stackabletech/opa-operator/issues/444
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)
> Backport Migrate "opa-bundle-builder" container name from <= 23.1 releases into 23.4

- CHANGELOG.md
- deploy/helm/opa-operator/crds/crds.yaml
- rust/crd/src/lib.rs
cherry picked from commit 691f8059a3727d614fada95adfae95b4aecd5885
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
Once the review is done, comment `bors r+` (or `bors merge`) to merge. [Further information](https://bors.tech/documentation/getting-started/#reviewing-pull-requests)
>  Add missing crd defaults to 23.4 

- Cargo.lock
- Cargo.toml
- deploy/helm/opa-operator/crds/crds.yaml
- rust/crd/Cargo.toml
- rust/operator-binary/Cargo.toml
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Switch to workspace dependencies

- deploy/helm/opa-operator/crds/crds.yaml
- docs/modules/opa/pages/usage-guide/listenerclass.adoc
- docs/modules/opa/partials/nav.adoc
- rust/crd/src/lib.rs
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> ListenerClass docs

- docs/modules/opa/pages/getting_started/installation.adoc
- docs/modules/opa/pages/index.adoc
Part of https://github.com/stackabletech/stackable-cockpit/pull/101
> docs: Update references

- docs/modules/opa/pages/index.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: Fix links

- Cargo.lock
- Cargo.toml
- rust/crd/src/lib.rs
- rust/operator-binary/Cargo.toml
- rust/operator-binary/src/controller.rs
- rust/operator-binary/src/main.rs
Part of https://github.com/stackabletech/product-config/issues/95
> refactor: Use updated product-config

- tests/templates/kuttl/cluster-operation/10-install-opa.yaml.j2
- tests/templates/kuttl/cluster-operation/20-stop-opa.yaml.j2
- tests/templates/kuttl/cluster-operation/30-pause-opa.yaml.j2
- tests/templates/kuttl/logging/02-install-opa.yaml.j2
- tests/templates/kuttl/resources/10-install-opa.yaml.j2
- tests/templates/kuttl/smoke/10-install-opa.yaml.j2
Part of https://github.com/stackabletech/issues/issues/481
> feat(test): pull policy IfNotPresent

- CHANGELOG.md
- deploy/helm/opa-operator/templates/_helpers.tpl
- deploy/helm/opa-operator/templates/deployment.yaml
- deploy/helm/opa-operator/templates/roles.yaml
- deploy/helm/opa-operator/values.yaml
Part of: https://github.com/stackabletech/issues/issues/501
> feat(helm): support labels in values.yaml

- deploy/helm/opa-operator/values.yaml
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Add Stackable vendor label to default values.yaml

- rust/user-info-fetcher/src/backend/keycloak.rs
- rust/user-info-fetcher/src/util.rs
fixes #509
```[tasklist]
```
```[tasklist]
```
> feat(UserInfoFetcher): better errors for HTTP errors

- rust/user-info-fetcher/src/util.rs
add status code and url to the error repsonses
```
2024-02-01T22:46:24.973885Z  WARN stackable_opa_user_info_fetcher: Error while processing request error=failed to get user information from Keycloak error.sources=[failed to get access_token, http response 401 for "https://keycloak.example.com/realms/master/protocol/openid-connect/token" with response body "{\"error\":\"invalid_client\",\"error_description\":\"Invalid client or Invalid client credentials\"}"]
```
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Improve user-info-fetcher error responses

- CHANGELOG.md
- docs/modules/opa/examples/getting_started/opa.yaml
- docs/modules/opa/examples/getting_started/opa.yaml.j2
- docs/modules/opa/pages/usage-guide/user-info-fetcher.adoc
- docs/modules/opa/partials/supported-versions.adoc
- tests/test-definition.yaml
- Add OPA 0.61.0
- Deprecate 0.57.0
- Removed 0.51.0
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Support OPA 0.61.0

- docs/modules/opa/pages/usage-guide/user-info-fetcher.adoc
These docs are still unpublished, so this is an addition to the _work in progress_.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: add a note about which service account role is required for UIF to access the Keycloak API

- docs/modules/opa/pages/index.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: update supported versions text

- tests/release.yaml
- tests/templates/kuttl/aas-user-info/00-patch-ns.yaml.j2
- tests/templates/kuttl/cluster-operation/00-patch-ns.yaml.j2
- tests/templates/kuttl/keycloak-user-info/00-patch-ns.yaml.j2
- tests/templates/kuttl/logging/00-patch-ns.yaml.j2
- tests/templates/kuttl/resources/00-patch-ns.yaml.j2
- tests/templates/kuttl/smoke/00-patch-ns.yaml.j2
- tests/test-definition.yaml
Part of stackabletech/issues#566.
OKD:
```
--- PASS: kuttl (203.45s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/aas-user-info_opa-latest-0.61.0_openshift-true (62.42s)
--- PASS: kuttl/harness/resources_opa-latest-0.61.0_openshift-true (22.26s)
--- PASS: kuttl/harness/smoke_opa-0.61.0_openshift-true (29.98s)
--- PASS: kuttl/harness/logging_opa-0.61.0_openshift-true (39.49s)
--- PASS: kuttl/harness/keycloak-user-info_opa-latest-0.61.0_keycloak-23.0.1_openshift-true (192.09s)
--- PASS: kuttl/harness/cluster-operation_opa-latest-0.61.0_openshift-true (40.89s)
```
Azure:
```
--- PASS: kuttl (187.70s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/smoke_opa-0.61.0_openshift-false (21.45s)
--- PASS: kuttl/harness/cluster-operation_opa-latest-0.61.0_openshift-false (29.68s) …
```
> tests: added namespace patch for openshift tests

- CHANGELOG.md
- deploy/helm/opa-operator/crds/crds.yaml
- docs/modules/opa/examples/getting_started/getting_started.sh
- docs/modules/opa/examples/getting_started/getting_started.sh.j2
- docs/modules/opa/pages/getting_started/first_steps.adoc
- docs/modules/opa/pages/getting_started/index.adoc
- docs/modules/opa/pages/getting_started/installation.adoc
- docs/modules/opa/pages/implementation-notes.adoc
- docs/modules/opa/pages/reference/crds.adoc
- docs/modules/opa/pages/reference/discovery.adoc
- docs/modules/opa/pages/usage-guide/configuration-environment-overrides.adoc
- docs/modules/opa/pages/usage-guide/index.adoc
- docs/modules/opa/pages/usage-guide/listenerclass.adoc
- docs/modules/opa/pages/usage-guide/logging.adoc
- docs/modules/opa/pages/usage-guide/monitoring.adoc
- docs/modules/opa/pages/usage-guide/policies.adoc
- docs/modules/opa/pages/usage-guide/resources.adoc
- docs/modules/opa/partials/supported-versions.adoc
- rust/crd/src/lib.rs
```[tasklist]
```
```[tasklist]
```
> docs: adjust formatting, add Pod overrides info

- deploy/helm/opa-operator/templates/roles-opa-builder.yaml
closes #551 
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: describe why the OPA builder ClusterRole needs to read ConfigMaps

- Cargo.toml
Part of https://github.com/stackabletech/issues/issues/601, https://github.com/stackabletech/issues/issues/557
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: bump cargo dependencies

- tests/templates/kuttl/logging/01-install-opa-vector-aggregator.yaml
Use Vector Helm chart version 0.34.0 (Vector 0.39.0) in the logging test
https://github.com/vectordotdev/helm-charts/blob/vector-0.34.0/CHANGELOG.md#vector-0340---2024-06-17
Implements stackabletech/docker-images#561
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Use Vector Helm chart version 0.34.0 in the logging test

- docs/modules/opa/examples/getting_started/getting_started.sh
- docs/modules/opa/examples/getting_started/getting_started.sh.j2
- docs/modules/opa/examples/getting_started/install_output.txt
- docs/modules/opa/examples/getting_started/install_output.txt.j2
- docs/modules/opa/pages/getting_started/installation.adoc
> docs(getting-started): update stackablectl op install output

- docs/modules/opa/pages/usage-guide/user-info-fetcher.adoc
> docs(user-info-fetcher): Add experimental warning to the top

- docs/modules/opa/pages/usage-guide/user-info-fetcher.adoc
Sibling PR: https://github.com/stackabletech/opa-operator/pull/607
> docs(user-info-fetcher): add experimental warning admonition at the top

- docs/modules/opa/pages/index.adoc
- docs/modules/opa/pages/usage-guide/logging.adoc
- docs/modules/opa/pages/usage-guide/monitoring.adoc
docs: remove home module from refs (stackabletech/documentation#637) / 23.11
> docs: remove home module from refs (stackabletech/documentation#637) / 23.11

- tests/templates/kuttl/logging/01-install-opa-vector-aggregator.yaml
Part of https://github.com/stackabletech/issues/issues/626
```[tasklist]
```
> chore: Bump Vector to 0.40.0

- tests/templates/kuttl/logging/01-install-opa-vector-aggregator.yaml
Upgrade the Vector aggregator in the logging tests
The Helm chart version 0.36.1 deploys Vector 0.41.1.
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: Upgrade the Vector aggregator in the logging tests

- docs/modules/opa/pages/getting_started/first_steps.adoc
- docs/modules/opa/pages/getting_started/index.adoc
- docs/modules/opa/pages/getting_started/installation.adoc
- docs/modules/opa/pages/index.adoc
- docs/modules/opa/pages/reference/discovery.adoc
- docs/modules/opa/pages/usage-guide/configuration-environment-overrides.adoc
- docs/modules/opa/pages/usage-guide/index.adoc
- docs/modules/opa/pages/usage-guide/logging.adoc
- docs/modules/opa/pages/usage-guide/monitoring.adoc
- docs/modules/opa/pages/usage-guide/policies.adoc
- docs/modules/opa/pages/usage-guide/user-info-fetcher.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Add descriptions

- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- deploy/helm/opa-operator/crds/crds.yaml
- rust/crd/src/user_info_fetcher.rs
- rust/operator-binary/src/controller.rs
Part of https://github.com/stackabletech/issues/issues/640
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: Update to operator-rs 0.76.0

- docs/modules/opa/pages/getting_started/first_steps.adoc
- docs/modules/opa/pages/getting_started/index.adoc
- docs/modules/opa/pages/getting_started/installation.adoc
- docs/modules/opa/pages/implementation-notes.adoc
- docs/modules/opa/pages/index.adoc
- docs/modules/opa/pages/reference/commandline-parameters.adoc
- docs/modules/opa/pages/reference/environment-variables.adoc
- docs/modules/opa/pages/usage-guide/configuration-environment-overrides.adoc
- docs/modules/opa/pages/usage-guide/index.adoc
- docs/modules/opa/pages/usage-guide/logging.adoc
- docs/modules/opa/pages/usage-guide/operations/graceful-shutdown.adoc
- docs/modules/opa/pages/usage-guide/operations/pod-disruptions.adoc
- docs/modules/opa/pages/usage-guide/user-info-fetcher.adoc
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> docs: improvements

- Cargo.lock
- tests/templates/kuttl/aas-user-info/10-install-opa.yaml.j2
- tests/templates/kuttl/cluster-operation/10-install-opa.yaml.j2
- tests/templates/kuttl/cluster-operation/20-stop-opa.yaml.j2
- tests/templates/kuttl/cluster-operation/30-pause-opa.yaml.j2
- tests/templates/kuttl/cluster-operation/40-restart-opa.yaml.j2
- tests/templates/kuttl/keycloak-user-info/10-install-opa.yaml.j2
- tests/templates/kuttl/logging/03-install-opa.yaml.j2
- tests/templates/kuttl/resources/10-install-opa.yaml.j2
- tests/templates/kuttl/smoke/10-install-opa.yaml.j2
- tests/test-definition.yaml
Allow using custom images in tests
> feat: Allow using custom images in tests

- CHANGELOG.md
- rust/operator-binary/src/controller.rs
- rust/operator-binary/src/main.rs
Part of https://github.com/stackabletech/issues/issues/211
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> Migrate to DeserializeGuard

- docs/modules/opa/examples/getting_started/getting_started.sh
- docs/modules/opa/examples/getting_started/getting_started.sh.j2
Part of https://github.com/stackabletech/issues/issues/611.
Depends on https://github.com/stackabletech/opa-operator/pull/653.
> chore(getting_started): Replace templating instructions with make

- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- deploy/helm/opa-operator/Chart.yaml
- docs/modules/opa/examples/getting_started/getting_started.sh
- docs/modules/opa/examples/getting_started/install_output.txt
- docs/templating_vars.yaml
- tests/release.yaml
> release: 24.11.1-rc2

- Cargo.lock
- Cargo.nix
- Cargo.toml
- crate-hashes.json
- rust/crd/Cargo.toml
- rust/crd/src/user_info_fetcher.rs
PR to fix unmaintained crate cargo deny errors
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: remove unmaintained derivative create and bump stackable-operator version

- .github/workflows/build.yml
- CHANGELOG.md
- Cargo.lock
- Cargo.nix
- Cargo.toml
- deploy/helm/opa-operator/Chart.yaml
- docs/modules/opa/examples/getting_started/getting_started.sh
- docs/modules/opa/examples/getting_started/install_output.txt
- docs/templating_vars.yaml
- tests/release.yaml
> release: 24.11.1

- tests/templates/kuttl/logging/01-install-opa-vector-aggregator.yaml
part of https://github.com/stackabletech/docker-images/issues/967
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: Update Vector to 0.43.1 in integration tests

- CHANGELOG.md
- docs/modules/opa/partials/supported-versions.adoc
- tests/test-definition.yaml
Part of https://github.com/stackabletech/docker-images/issues/998
```[tasklist]
```
```[tasklist]
```
```[tasklist]
```
> chore: bump latest version to 1.0.1

- docs/modules/opa/pages/index.adoc
Add airflow, HDFS and superset to supported products
> Docs: add airflow, HDFS and superset supported products

- docs/modules/opa/pages/usage-guide/user-info-fetcher.adoc
Document AD user filter implementation details as requested by this [comment](https://github.com/stackabletech/opa-operator/issues/702#issuecomment-3036657012).
> docs: describe AD user filter

- CHANGELOG.md
- deploy/helm/opa-operator/templates/roles.yaml
> fix: Backport Add RBAC permission to patch events

- tests/templates/kuttl/logging/01-install-opa-vector-aggregator.yaml
- tests/templates/kuttl/logging/test_log_aggregation.sh
Part of https://github.com/stackabletech/docker-images/issues/1233
```
--- PASS: kuttl (101.92s)
--- PASS: kuttl/harness (0.00s)
--- PASS: kuttl/harness/logging_opa-1.4.2_openshift-false (100.05s)
--- PASS: kuttl/harness/logging_opa-1.0.1_openshift-false (101.91s)
PASS
```
> chore: Bump vector version for 25.11.0
